### PR TITLE
Delete unused pr_consistency workflow

### PR DESCRIPTION
**Pull request by pllim**
This is the first step for resolving #181

### CODE REVIEW

**Comment by bsipocz** [comment]
Just because core drops something, it doesn't mean it should go.

I do use this for astroquery, pyvo and such.

**Comment by pllim** [comment]
But this workflow is specifically for `astropy`, no? The scripts are still there.

**Comment by bsipocz** [comment]
Ahh, workflow. Yes, I don't need that, but the scripts.

**Comment by pllim** [comment]
Oh, no. I am not touching the scripts. Don't worry. 😉

**Review by astrofrog — APPROVED** [review]

**Pull request merged**
