### PR TITLE
[WIP] Contributor plots

### PR DESCRIPTION
**Pull request by bourque**
This PR introduces `contributors-plots.py`, which creates plots showing the number of contributors to `astropy`-affiliated packages over time.  This work was done as part of the `.astronomy` 2018 hack day.  The original idea for this is attributed to @eteq !

Some lingering questions/issues include:
1. Right now this just uses default `matplotlib` style plots.  It would perhaps be better to do this in `bokeh` or advanced `matplotlib` instead.
2. Currently this isn't smart enough to exclude cases where someone has changed their GitHub username.  In those cases, if someone is operating under more than one username, they would be counted more than once in the resulting plots.
3. Eventually, it would be nice to expand this out to the whole "`astropy` python ecosystem" as @eteq suggests.
4. This code just saves the plots to a locally directory called `contribution-plots`, but perhaps there is a better place to store this data.
5. This is not at all tested or contains any error handling for corner cases (e.g. user does not have supplied their GitHub auth token).

### CODE REVIEW

**Comment by bsipocz** [comment]
@bourque - Why the plot for astropy only goes up to ~100? should be more like ~240+

**Comment by bourque** [comment]
@bsipocz Thanks for catching that.  Let me look into it, and tag this as a WIP.  Like I said, this effort was part of a hack day so there are likely some shortcomings.

**Comment by bsipocz** [comment]
and it's a super useful hack :)

**Comment by bourque** [comment]
I'm not quite sure what is going on here.  Though the main page of the `astropy` repo claims 266 contributors, when I visit the [contributors page](https://github.com/astropy/astropy/graphs/contributors) it only lists 100, which is what is also returned from the request to https://api.github.com/repos/astropy/astropy/stats/contributors.  The [GitHub REST API](https://developer.github.com/v3/repos/statistics/) warns that the statistics do not include merge commits, but i'm not sure that would account for the 166 people.

I thought that perhaps the REST API was returning the results in pages, but when I try `https://api.github.com/repos/astropy/astropy/stats/contributors?page=2`, it doesn't seem to alter the returned results.

**Comment by bsipocz** [comment]
The contributors page is always limited to show the top 100 people. For the webpage and all other stats we actually always used the full git log instead, as not all the contributors are on github any more, or their e-mail address they made the contributions with might not recognized by github. Maybe it's also possible to do with the API, but I don't know how.

**Comment by pllim** [comment]
Thanks, but I think there are better places out there now for such contributions.

https://devstats.scientific-python.org/

**Pull request closed without merging**
