### PR TITLE
Add a script to find the next PR number for the changelog

### PR DESCRIPTION
**Pull request by astrofrog**
Taking the fun out of it 😆 

```
$ python next_pr_number.py 
Next PR number: 6104
```

cc @pllim @bsipocz

### CODE REVIEW

**Comment by pllim** [comment]
Why stop here? Have people just enter `[help me astrobot]` at the end of their change log without the PR number, and then @astrobot would submit a PR to their PR with PR number added... :robot: :ghost:

**Comment by pllim** [comment]
So, are we going to add in contributing doc that contributor should use this before submitting the PR?

**Comment by astrofrog** [comment]
I think that's too much to ask from average contributors (installing the command-line script). I think this is mainly for developers who open many PRs. Otherwise it's easy enough now for maintainers to edit a PR through the GitHub GUI and add the PR number for PRs if needed. I don't want to raise the bar for contributors by asking them to install this.

**Comment by pllim** [comment]
Fair enough.

**Comment by bsipocz** [comment]
I would also add that we don't ask for changelog entry by default in the contribution guide, but tell new contributors to wait for a maintainer to guide them whether it needs an entry at all, and if yes, which section it should go into.

**Comment by saimn** [comment]
And with the same idea implemented in a git pre-commit hook, which replaces `GUESSPR` (any better idea ?) in the `CHANGES.rst` file just before committing !  (using `-v` is recommended to check the result). Should I open a PR with this superb script ?
https://gist.github.com/saimn/67d7b2af5031a32dc9903be0d858616c

**Pull request merged**
