### PR TITLE
Scripts to check changelog consistency

### PR DESCRIPTION
**Pull request by astrofrog**
This is still a work in progress, but the idea is to have a script that can check that milestones in PRs match the changelog and also match which maintenance branch the PR was backported to. At the moment, this just checks that milestones match the changelog section, and there's still some missing logic. I'm just putting this up here to make sure no one else tries to duplicate this effort :)

Example output so far:

```
v1.1.1: 1 out of 5 pull requests had issues:
  Milestone for pull request #4452 is v1.0.8 but is in the changelog section for v1.1.1
v1.1.2: 7 out of 16 pull requests had issues:
  Milestone for pull request #4489 is v1.0.9 but is in the changelog section for v1.1.2
  Milestone for pull request #4514 is v1.0.9 but is in the changelog section for v1.1.2
  Milestone for pull request #4539 is v1.2.0 but is in the changelog section for v1.1.2
  Milestone for pull request #4650 is v1.0.9 but is in the changelog section for v1.1.2
  Milestone for pull request #4468 is v1.0.9 but is in the changelog section for v1.1.2
  Milestone for pull request #4468 is v1.0.9 but is in the changelog section for v1.1.2
  Pull request #4678 is in version v1.1.2 but has no milestone set
v1.1.3: 1 out of 5 pull requests had issues:
  Milestone for pull request #4786 is v1.0.10 but is in the changelog section for v1.1.3
v1.2: 3 out of 69 pull requests had issues:
  Pull request #4671 is in version v1.2 but has no milestone set
  Milestone for pull request #4579 is v1.1.2 but is in the changelog section for v1.2
  Milestone for pull request #4720 is v1.1.3 but is in the changelog section for v1.2
```

* [x] check for PRs that aren't mentioned in the changelog at all (take into account the affects-dev label)
* [x] check which branches a PR has been backported to
* [ ] check for PR numbers mentioned in the changelog and not found on GitHub (although some of those could be issues)
* [x] only check PRs merged into master

cc @eteq

### CODE REVIEW

**Comment by embray** [comment]
Awesome--I always wanted to do something like this. Seems obvious.

**Comment by astrofrog** [comment]
I've now updated the scripts, and will be spending some time next week going through individual problematic entries. But in the mean time, @embray, feel free to check over the logic in ``4.check_consistency.py`` to see if you agree!

**Comment by astrofrog** [comment]
@eteq - this is ready for review!

**Comment by astrofrog** [comment]
@eteq - just for info, this now also provides the backport commands. Given that ``suggest_backports.py`` is broken currently (and I don't have time to investigate), I'm using this instead. After the initial run of ``get_merged_prs``, this is really fast:

```
$ python 4.check_consistency.py
Main report:
#5072 (Milestone: v1.2.0)
  - Pull request was not included in branch v1.2.x. You can backport it with:
Backports to v1.2.x (in merge order)
git cherry-pick -m 1 af013eff6e336b4728dfae199c0f2c4f7ef0f2f2
```

**Comment by astrofrog** [comment]
I used this in production for the 1.2 release, so I'm going to go ahead and merge this and we can always make tweaks to it during the next release cycle.

**Pull request merged**
