### PR TITLE
added add_to_changelog.py

### PR DESCRIPTION
**Pull request by eteq**
This is a straightforward tool that generates a new section for the astropy changelog.  Just use it as it says in the header docstring.

(Note that this will be used in a forethecoming modification to the astropy release isntructions)

### CODE REVIEW

**Comment by astrofrog** [comment]
We should have an option to indicate it's a bugfix release, in which case some of the sections aren't needed.

**Comment by astrofrog** [comment]
Can you make the script modify the changelog?

**Comment by astrofrog** [comment]
One issue - it doesn't seem to add all the sections - if I run it with

```
python add_to_changelog.py CHANGES.rst 1.0.11
```

I get:

```
1.0.11 (unreleased)
-------------------

New Features
^^^^^^^^^^^^

- ``astropy.coordinates``

- ``astropy.io.ascii``

- ``astropy.io.fits``

- ``astropy.table``

- ``astropy.tests``

- ``astropy.units``

- ``astropy.utils``

API Changes
^^^^^^^^^^^

- ``astropy.coordinates``

- ``astropy.io.ascii``

- ``astropy.io.fits``

- ``astropy.table``

- ``astropy.tests``

- ``astropy.units``

- ``astropy.utils``

Bug Fixes
^^^^^^^^^

- ``astropy.coordinates``

- ``astropy.io.ascii``

- ``astropy.io.fits``

- ``astropy.table``

- ``astropy.tests``

- ``astropy.units``

- ``astropy.utils``

Other Changes and Additions
^^^^^^^^^^^^^^^^^^^^^^^^^^^

- Nothing changed yet.
```

There are many sections missing.

**Comment by eteq** [comment]
Sorry, lost track of this @astrofrog.  One at a time:

> We should have an option to indicate it's a bugfix release, in which case some of the sections aren't needed.

Which sections aren't needed?  In the past we *sometimes* have had new features/API changes/other in bugfixes in unusual circumstances.  So that's why I opted to leave it in...

> Can you make the script modify the changelog?

Good point - see the new commit which adds it as an option (off by default for safety).

> One issue - it doesn't seem to add all the sections - if I run it with

I'm not seeing that when I run it locally - I get all the appropriate sections.  Could you have an old version of ``CHANGES.rst``?  That's what it uses to figure out the sections...

**Comment by astrofrog** [comment]
Was trying out the review feature and marked this as 'requires changes' (even though it doesn't really if too hard). But just to try out the feature!

**Comment by eteq** [comment]
Yes! Done in commit 863e79a .  Going to bypass you accepting and merge this as-is, though, so that I can use it ;)

**Pull request merged**
