### PR TITLE
Initial version of script to update astropy-helpers in all repositories

### PR DESCRIPTION
**Pull request by astrofrog**

### CODE REVIEW

**Comment by bsipocz** [comment]
In a few repos there was already an open PR with the update, but wasn't merged due to some issues.

Would it be possible to check for that first? Although I think it will be less of an issue in the future if a bot or someone runs this script right after the helpers release.

**Comment by astrofrog** [comment]
@bsipocz - yes, sorry about that! I'm not sure how easy it will be to automate the checking efficiently, but I'll take a look. I think it would make sense to go all-automatic though.

**Comment by bsipocz** [comment]
Yes, thinking about this a bit more it won't be an issue in the future as none of the maintainers are as fast to open a PR with a helpers update as the person releasing the helpers, or the bot that picks it up automatically :)

**Comment by bsipocz** [comment]
Also a bit :+1: for this, as I think it address a few concerns about the helpers that was raised at pyastro16.

**Comment by eteq** [comment]
I'm a bit confused as to *who* is supposed to run this, though?  I think it needs a docstring explaining the workflow...

**Comment by astrofrog** [comment]
@eteq - I agree it needs documentation - this is a WIP for now. Basically I think the person who releases the helpers should run this.

**Comment by astrofrog** [comment]
Note to self: add

https://github.com/chandra-marx/marxs
https://github.com/hamogu/astrospec
https://github.com/hamogu/psfsubtraction

to the list of packages to process (requested by @hamogu). The script can include a list of manual additions.

**Comment by bsipocz** [comment]
@astrofrog - Also please add https://github.com/astropy/regions

**Comment by bsipocz** [comment]
Also please add https://github.com/astropy/package-template

**Comment by astrofrog** [comment]
@eteq - I added a note to explain that this is not to be run by affiliated package maintainers

**Pull request merged**
